// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnULHUDq8vrJQdXONDH1dcX5M_bk9FdVw',
    appId: '1:1069253910800:web:985880be7cbff8f9b18595',
    messagingSenderId: '1069253910800',
    projectId: 'trainingcourse-b7172',
    authDomain: 'trainingcourse-b7172.firebaseapp.com',
    storageBucket: 'trainingcourse-b7172.appspot.com',
    measurementId: 'G-ESEGVNXZ3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2EpmCHeJKjOE6qEFXKMh2qta5aBZFCw4',
    appId: '1:1069253910800:android:e48707be72dbbc9db18595',
    messagingSenderId: '1069253910800',
    projectId: 'trainingcourse-b7172',
    storageBucket: 'trainingcourse-b7172.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkkttJwln5lWUUQG6LwfhQEq1RcH9OIfc',
    appId: '1:1069253910800:ios:64a08871c5c7fd5db18595',
    messagingSenderId: '1069253910800',
    projectId: 'trainingcourse-b7172',
    storageBucket: 'trainingcourse-b7172.appspot.com',
    iosBundleId: 'y',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkkttJwln5lWUUQG6LwfhQEq1RcH9OIfc',
    appId: '1:1069253910800:ios:11c933678b113f1fb18595',
    messagingSenderId: '1069253910800',
    projectId: 'trainingcourse-b7172',
    storageBucket: 'trainingcourse-b7172.appspot.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnULHUDq8vrJQdXONDH1dcX5M_bk9FdVw',
    appId: '1:1069253910800:web:6488fcd70d452bbab18595',
    messagingSenderId: '1069253910800',
    projectId: 'trainingcourse-b7172',
    authDomain: 'trainingcourse-b7172.firebaseapp.com',
    storageBucket: 'trainingcourse-b7172.appspot.com',
    measurementId: 'G-MKBBFJWXYN',
  );
}
